### ISSUE TITLE
没有身份认证和内容加密？

### ISSUE THREAD

**Issue by SankHyan24** [alx696/polong-core#1]
没有身份认证和内容加密，直接smurf攻击不就能窃听了，而且你这个貌似直接能在内网暴露出来？感觉你这个东西想法没考虑全面，漏洞很多。

**Comment by shiwaimanong** [comment]
标志身份的唯一编码是通过证书生成的无法伪造. 当使用TLS之类的加密通道时, 数据在传输过程中已经加密了. 去中心化的特点就是没有集权, 最终决定权都在用户手上. 没有内网穿透这个就没有任何意义了!
这是一个实验性的东西, 肯定存在考虑不周的地方. 如果你愿意帮助改进, 可以提出具体问题并给出解决方案.
